# Generated by Django 2.2.5 on 2019-11-13 22:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191111_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchased_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 22, 22, 1, 207692, tzinfo=utc)),
        ),
    ]
